services:
  dns:
    build: ./dns
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/named.conf.local:/etc/bind/named.conf.local
      - ./dns/db.asa.br:/etc/bind/db.asa.br
    networks:
      - rede-interna
        
  proxy:
    build: ./proxy
    container_name: proxy-server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rede-externa
      - rede-interna
    depends_on:
      - web1
      - web2

  web1:
    build: ./web1
    container_name: web1
    networks:
      - rede-interna  

  web2:
    build: ./web2
    container_name: web2
    networks:
      - rede-interna
        
networks:
  rede-interna:
    driver: bridge
  rede-externa:
    external: true
# docker network create <nome_da_network>